version: "3.9"
services:
  listapp:
    platform: linux/x86_64
    build: .
    image: listapp:dev
    container_name: listapp-container
    volumes: 
      - ./:/listapp
    expose:
      - 8182
    ports:
      - 8182:8182
    restart: always
    depends_on:
      - db
    env_file:
      - ${HOME}/listapp-env/.env
  
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: listapp-db-container
    environment:
      MYSQL_ROOT_PASSWORD: Abix.360*
      MYSQL_DATABASE: listapp
      MYSQL_TCP_PORT: 3307
    volumes:
      - ../listapp_db:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307

volumes:
  listapp_db: